:stem: latexmath
= Kernel Smoothing

== Overview

This application takes DTM file(s) in new format as input and will return DTM file(s) with a smoothing applied to the elevation layer.
Min and max values are updated accordingly.

A kernel parameter allow to select several values among several known kernel and two custom kernel.

Coefficient values for known kernels are :

[stem]
++++
\displaylines{
flat =
\begin{bmatrix}
1 & 1 & 1 \\
1 & 4 & 1 \\
1 & 1 & 1
\end{bmatrix} \\

plus = \begin{bmatrix}
0 &1& 0 \\
1& 4& 1 \\
0& 1& 0
\end{bmatrix} \\


x = \begin{bmatrix}
1 & 0 & 1\\
0 & 4 & 0\\
1 & 0 & 1
\end{bmatrix} \\

basic\_gauss =
\begin{bmatrix}
1 & 4 & 7 & 4 & 1 \\
4 & 16 & 26 & 16 & 4 \\
7 & 26 & 41 & 26 & 7\\
4 & 16 & 26 & 16 & 4\\
1 & 4 & 7 & 4 & 1
\end{bmatrix} \\
}
++++

If a kml or shapefile are given as parameter only value inside the shapes are smoothed (but values outside are taken into account for the smoothing)

By default, the name of the output file is i_path with the suffix "-smoothed".
The size of the smoothed window is (3, 3).
No zone selected.

[IMPORTANT]
If a *custom kernel* is chosen it is up to the user to : *open* the smoothing_process_kernel.py file delivered in globe directory and *modify* in it the `custom_kernel` or `custom_kernel2` coefficients values

include::example$generated/dtm/transform/kernel_smoothing_params.adoc[]
