= Reproject and Update Bounding Box

== Overview

This process allow to change the projection, the bounding box and/or spatial resolution of a DTM and reproject its data on the computed grid.

The function is based on the warp function of gdal. The resampling method available depends on the nature of the layer processed.

[IMPORTANT]
====
This process was only tested fully with files with only one CDI contributing. Use it for files with several contributors with caution

By default, in order to handle the different kind of EMODnet layers the following parameters are set by default :

* for CDI, interpolation is set to mode which mean the cell will take the value of the dominant CDI at that point

* for Stdev and value_count and interpolation_flag layers, interpolation is set to near by default which mean that the value will be taken from the nearest cell

====

Note only a few methods are avalaible for each layer, the list of resampling methods available in GDAL  are:

* near: nearest neighbour resampling (default, fastest algorithm, worst interpolation quality).
* bilinear: bilinear resampling.
* cubic: cubic resampling.
* cubicspline: cubic spline resampling.
* lanczos: Lanczos windowed sinc resampling.
* average: average resampling, computes the weighted average of all non-NODATA contributing pixels.
* mode: mode resampling, selects the value which appears most often of all the sampled points.
* max: maximum resampling, selects the maximum value from all non-NODATA contributing pixels.
*  min: minimum resampling, selects the minimum value from all non-NODATA contributing pixels.
* med: median resampling, selects the median value of all non-NODATA contributing pixels.
* q1: first quartile resampling, selects the first quartile value of all non-NODATA contributing pixels.
* q3: third quartile resampling, selects the third quartile value of all non-NODATA contributing pixels.
* sum: compute the weighted sum of all non-NODATA contributing pixels (not available for now)

include::example$generated/dtm/transform/update_boundingbox_params.adoc[]
