= Gravimetry Processing

== Overview
This tool processes TECHSAS gravimetry files (.mag.nc).

====
**Note**: input files (.mag.nc) must contain navigation data.
====

The output file will contain new variables generated by the following steps :

=== 1 - Measurements processing

* *Apply filter delay* : measurement times are shifted taking into account the gravimeter filter delay

* (Optional) *Correction of the spring stiffness coefficient* : the spring stiffness coefficient evolves, this parameter enables to apply a "reel" spring elongation value. All measurements will be corrected by the translation:
[source,]
----
observed_gravity = observed_gravity x real_spring_stiffness / install_spring_stiffness
----

* *Drift correction* : to get absolute gravity, measurements are tied to reference values (from reference gravity stations).
[source,]
----
drifted_gravity = observed_gravity + reference_gravity + drift
----

For more details see : http://en.data.ifremer.fr/All-about-data/Themes/Geophysics/Gravimetry

=== 2 - Eotvos correction
* Compute Eotvos correction from platform navigation data :
[source,]
----
eotvos_correction = 7.5029 * speed * cos(latitude) * sin(heading) + 0.0042 * speed²
----

* Apply Eotvos correction to get corrected gravity :
[source,]
----
corrected_gravity = drifted_gravity + eotvos_correction
----

=== 3 - Theoretical gravity
* Compute theoretical gravity from platform navigation data :
[source,]
----
theoritic_gravity = 978032.7 + 5185.92 * sin(latitude)² - 5.67 * sin(2*latitude)²
----

=== 4 - Free air anomaly
* Compute free air anomaly :
[source,]
----
free_air_anomaly = corrected_gravity - theoretic_gravity
free_air_anomaly = drifted_gravity + eotvos_correction - theoretic_gravity
----

include::example$generated/sensor/process/techsas_gravi_params.adoc[]
