= Turn Filter

== Overview

This tool detects turns in navigation data from heading and/or speed variations. It returns straight lines defined by start and end dates.

=== Algorithm

For each navigation point, a filtering method is applied on a window around the point to determine if it is inside a turn or not.

=== Parameters

* *Heading* period (sec) and threshold (°)
* *Speed* period (sec) and threshold (m/s)
* *Filter method* : method applied on window to get the value to compare with the threshold :
    ** *gap* : tested value is the difference between first and last window values
    ** *std* : tested value is the standard deviation
    ** *weighted_std* : tested value is a weighted standard deviation, navigation points close to the window center have more weight to calculate the standard deviation.
* *Minimum duration* (sec) : minimum duration of cut line (= straight line) exported in cut file.

=== Output

This tool can return a **cut file (.cut)** or edit input file status variable.

include::example$generated/sensor/process/turn_filter_params.adoc[]
