= Merge/Fit BSAR incidence curves

== Overview
Merges all curves by incidence angles and creates a new MeanBSModel with a single common mode.
Value counts are summed up, and weghted mean values are computed.
Optionnaly, a gsab fitting is applied to the merged curve.

Use split bsar process first to fit incidence curves per acquisition mode individually.

== Parameters
__use_raw_data__: If True, use raw mean backscatter values and counts as weights; otherwise, use smoothed mean values.

__apply_gsab_fitting__: If True, apply auto 6 parameters gsab fitting.

== References
Lamarche, G., Lurton, X., Verdier, A.-L., Augustin, J.-M., 2011. "Quantitative characterisation of seafloor substrate and bedforms
using advanced processing of multibeam backscatterapplication to cook strait, new zealand. Continental Shelf Research 31 (2),
S93–S109."
https://doi.org/10.1016/j.csr.2010.06.001


    Specular level A (dB/m2)
    Specular angular extent B (deg)
    Lambert reference C (dB/m2)
    Lambert decrement D
    Transitory level E (dB/m2)
    Transitory angular extent F (deg)

    dB Units choosen to fit with Sonarscope. Before used in the gsab standard formula, coeffs should be converted in natural energy and angles devided by 2.

[stem]
++++
gsab(x) = 10 * log_10(A * exp(-(x^2) / (2 * B^2)) + C * cos^D(x) + E * exp(-(x^2) / (2 * F^2)))
++++
