:last-update-label!:

= How to add new process in GLOBE Pytoolbox

== Introduction
This document describes how to add a new PyAT process into the GLOBE Pytoolbox.

== (Optional) Link GLOBE to PyAT
By default, GLOBE uses its embedded PyAT project (in /pyat).

To use an other version of PyAT, for example a branch of https://gitlab.ifremer.fr/fleet/pyat, change the GLOBE preference value : 
``` 
Preferences > PyToolbox > PyAT configuration file
``` 
 
=> Select the *pyat/globe.conf* of the PyAT project to use 


[NOTE]
====
About *PyAT*  : 

* The project contains **GIT submodules**, which have to be setup after first clone ('git submodule init', 'git submodule update'...).
* *Miniconda environments* are described in */requirements* directory. They can be installed with the script *create_anaconda_environments.py*. 

For example :
``` 
create_anaconda_environments.py -target dev
``` 
====

If the selected PyAT required a specific miniconda environment, set the preference : 
``` 
Preferences > PyToolbox > Conda environment
``` 


== Set up required files
Each process available from the PyToolbox needs theses files: 

=== Configuration file (.conf)
JSON file that contains paths to other files (help, python script...) and describes the process parameters. It is used by GLOBE to build the wizard that enables user to select parameters.  

_=> See files under : */pyat/app/conf/example/*._ 

[IMPORTANT]
====
This file have to be referenced in **globe.conf** file.
====

=== Help (.html)
Help document displayed in GLOBE : referenced in configuration file with the key **"help"**.

_=> See files under : */pyat/app/help/example/* ._

[TIP]
====
Most of help documents are generated from an Asciidoc file (.adoc).

Use the tool : https://asciidocfx.com/ to create an Asciidoc file and click on *HTML > Save as* to generate the HTML file. 
====


=== Launch script (_app.py)
Python file called by GLOBE : referenced in configuration file with the key **"file"**.

_=> See file : */pyat/app/example/process_skeleton.py* ._

[NOTE]
====
This script is the entry point from GLOBE.

The *main* method is called with a *parameter file (.json)* generated by GLOBE when the user launch the process. 

PyAT provides an utility class (__pyat.app.application_utils__) to parse the parameter file, initialize a class with parameters and execute the *call* method of this class.
====

=== (Optional) Process script (.py)
Independent python script with the core of the code to execute. This script is called from the launch script. It is not mandatory, in fact the code to be executed can be implemented in launch script but it is not recommended.

== Launch scripts outside GLOBE

The launch scripts can be called outside GLOBE, the easiest way is to relaunch the command displayed in GLOBE console and modify the parameter file (.json) generated in cache. 

