= Merge with slope

== Overview

The principle of this application is to allow to merge two dtm based on the local slope values.
This operation is usefull to make grid on an area with big slopes differences :

* One grid is made by the user for flat area and taken as reference grid (slope less than a minimum value)

* One grid is made by the user for steep area and taken as secondary grid

The resulting grid will take the first values on flat area, the seconds on steep area and a slope based interpolation in mixted area

include::example$generated/dtm/merge/merge_with_slope_params.adoc[]

This application takes two dtm as input :

* one is named "reference"

* the second on is named "secondary"

Two parameters min_slope and max_slope are given in degrees.

== Processing

Slope is computed over the reference input, then output is computed given the following principle :

* if slope<min_slope then output is set to the reference_value

* if slope > max_slope then output is set to the secondary_value

* otherwise output is computed by linear interpolation : output= f*reference_value + (1-f)*secondary_value.
With f = (slope-min_slope)/(max_slope-min_slope)

[NOTE]
====
* For CDI layer in case of interpolation, output is given to the dominant with respect to the f factor (output= reference_value if f<0.5)
* For min/max layer in case of interpolation value is set by computing the min/max value of each input
====

