= Backscatter angular renormalization

== Overview
Compute a backscatter renormalization to remove angular dependency.
Based on statistic curves, backscatter offsets are computed and applied to file inputs in order to minimize backscatter gaps between sectors and optionnaly compensate for incidence angular dependency fitting a constant (typically -20) mean response.

The full processing pipeline is fully detailed in the article "Acoustic backscatter processing in GLOBE: an open-source software for echo sounder data analysis" (https://doi.org/10.3389/frsen.2025.1574129)

== Algorithm parameters
The computation parameters are :

* _Mean model file (mean_model_file)_ is the .bsar.nc file containing mean backscatter response by angle previously computed with the "Backscatter statistical model response" tool.

* _Use snippets_ to recompute mean backscatter value by detection. Mean backscatter values by detection are stored in Sonar/BeamGroup1/Bathymetry/detection_backscatter_r variable in XSF file. This variable contains precomputed data and will be used to store corrected bs values. The raw snippets bs values can be used with this option to relaunch process from uncorrected values.

* _Apply compensation_ allows to choose if the angular compensation by incidence angle must be applied to the raw backscatter values or if only the residuals part is applied. If false, only compensates for sector and antenna differences without changing the angular response (equivalent to a calibration with a BSCorr).

* _Reference backscatter level (reference_level)_ specifies the target mean backscatter level to reach after angular compensation. The mean model will be shifted to reach this target level.

* _Reference Dtm (i_dtm)_ specifies the .dtm.nc file used to estimate incidence angle with the seafloor by detection.
