= Peak and Holes Finder

== Overview

This application regroups a set of algorithm helping to find outliers in a dtm.

All the algorithm will have the same behaviour : apply detection method to outliers then for each detection
generate a csv file in a format that is loadable into Globe. Then it is adviced to do a go to each detection, inspect it and decide to keep or reject this detection

[NOTE]
This algorithm is a preliminary work, and it could generate false detection for example outside the source dataset

The algorithms avalaible are :

* Gradient algorithm : this will compute a gradient over dtm, compare it to a smoothed gradient (with a percentile filter) in order to allow local slope variations  and detect local outliers in gradient.

* Percent of elevation detection method : detect elevation variation with a threshold expressed as percent of local depth

* Stdev variation detection : compute local stdev and threshold stdev higher than the parameter value

* Hole detection : detect invalid region and eliminate the ones bigger (in pixel) that the associated parameter

include::example$generated/dtm/analyse/peak_finder_params.adoc[]
