site:
    title: PYAT Docs
    start_page: pyat::index.adoc
content:
    sources:
        -   url: ./..
            branches: HEAD
            start_path: /documentation
ui:
    bundle:
        url: C:/dev/documentation/antora-ui-default/src
        snapshot: true
